[pytest]


# Allow imports like:
# from app.main import app
#
# because backend/ is the Python root
pythonpath = .


# Test file naming convention
python_files = test_*.py


# Test location
testpaths =
    tests


# Default pytest options
#
# -v:
# verbose output
#
# html:
# generate browser report
#
# cov:
# calculate code coverage
#
addopts =
    -v
    --html=test-report.html
    --self-contained-html
    --cov=app
    --cov-report=term-missing
    --cov-report=html